---
version: "3"

tasks:
  format:
    cmds:
      - fd '.nix' | xargs nixfmt

  osSwitch:
    cmds:
      - nh os switch -H system .

  homeSwitch:
    cmds:
      -  nh home switch -c user .

  switch:
    cmds:
      - task: osSwitch
      - task: homeSwitch

  switch-update:
    cmds:
      - task: update
      - task: switch

  update:
    cmds:
      - nix flake update

  osTest:
    cmds:
      - nh os test -H system .

  test:
    cmds:
      - task: osTest
      - task: homeSwitch
