---
version: "3"

tasks:
  format:
    cmds:
      - fd '.nix' | xargs nixfmt

  os-switch:
    cmds:
      - nh os switch .

  switch:
    cmds:
      - task: os-switch

  switch-update:
    cmds:
      - task: os-update
      - task: os-switch

  os-update:
    cmds:
      - nix flake update

  os-test:
    cmds:
      - nh os test .

  test:
    cmds:
      - task: os-test
