---
version: "3"

tasks:
  format:
    cmds:
      - fd '.nix' | xargs nixfmt

  os-switch:
    cmds:
      - nh os switch -H system .

  home-switch:
    cmds:
      - nh home switch -c user .

  home-update:
    cmds:
      - nh home switch -uc user .

  switch:
    cmds:
      - task: os-switch
      - task: home-switch

  switch-update:
    cmds:
      - task: os-update
      - task: os-switch
      - task: home-update

  os-update:
    cmds:
      - nix flake update

  os-test:
    cmds:
      - nh os test -H system .

  test:
    cmds:
      - task: os-test
      - task: home-switch
