{ self, config, pkgs, inputs, vars, ... }:

{

  imports = [
    ./../../modules/home-manager/editors
    ./../../modules/home-manager/shell
    ./../../modules/home-manager/term
    ./../../modules/home-manager/cli
    ./../../modules/home-manager/desktop
  ];

  # Home Manager needs a bit of information about you and the paths it should
  # manage.
  home = {
    username = vars.username;
    homeDirectory = "/home/${vars.username}";
    stateVersion = "24.11"; # Please read the comment before changing.
  };

  home.packages = [
    pkgs.hello
    pkgs.fastfetch
    pkgs.git-crypt
    pkgs.keepassxc
    pkgs.nextcloud-client

  ];

  # Home Manager is pretty good at managing dotfiles. The primary way to manage
  # plain files is through 'home.file'.
  home.file = {
    # # Building this configuration will create a copy of 'dotfiles/screenrc' in
    # # the Nix store. Activating the configuration will then make '~/.screenrc' a
    # # symlink to the Nix store copy.
    # ".screenrc".source = dotfiles/screenrc;

    # # You can also set the file content immediately.
    # ".gradle/gradle.properties".text = ''
    #   org.gradle.console=verbose
    #   org.gradle.daemon.idletimeout=3600000
    # '';
  };

  # Home Manager can also manage your environment variables through
  # 'home.sessionVariables'. These will be explicitly sourced when using a
  # shell provided by Home Manager. If you don't want to manage your shell
  # through Home Manager then you have to manually source 'hm-session-vars.sh'
  # located at either
  #
  #  ~/.nix-profile/etc/profile.d/hm-session-vars.sh
  #
  # or
  #
  #  ~/.local/state/nix/profiles/profile/etc/profile.d/hm-session-vars.sh
  #
  # or
  #
  #  /etc/profiles/per-user/mads/etc/profile.d/hm-session-vars.sh
  #
  home.sessionVariables = {
    # EDITOR = "emacs";
  };

  # Let Home Manager install and manage itself.
  #programs.home-manager.enable = true;

  # Enable direnv for nix
  # For more information see: https://github.com/nix-community/nix-direnv
  programs = {
    direnv = {
      enable = true;
      enableBashIntegration = true; # see note on other shells below
      nix-direnv.enable = true;
    };

    bash.enable = true; # see note on other shells below
  };

  programs.tmux = {
    enable = true;
  };

  programs.ssh = {
    # all my ssh private key are generated by `ssh-keygen -t ed25519 -C "name@example.com"`
    # the config's format:
    #   Host —  given the pattern used to match against the host name given on the command line.
    #   HostName — specify nickname or abbreviation for host
    #   IdentityFile — the location of your SSH key authentication file for the account.
    # format in details:
    #   https://www.ssh.com/academy/ssh/config
    enable = true;
    addKeysToAgent = "1d";
    extraConfig = ''
      # a private key that is used during authentication will be added to ssh-agent if it is running
      AddKeysToAgent yes

      Host 192.168.*
        # allow to securely use local SSH agent to authenticate on the remote machine.
        # It has the same effect as adding cli option `ssh -A user@host`
        ForwardAgent yes
        # romantic holds my homelab~
        # IdentityFile /etc/agenix/ssh-key-romantic
        # Specifies that ssh should only use the identity file explicitly configured above
        # required to prevent sending default identity files first.
        #IdentitiesOnly yes

      Host Docker
        HostName 192.168.60.5
        Port 2345
        ForwardAgent yes
    '';
  };
  services.ssh-agent.enable = true;

  programs.git = {
    enable = true;
    userEmail = "mads@plikki.com";
    userName = "Hexamo";
  };


}
