{
  imports = [
    ./accounts-daemon.nix
    ./acipd.nix
    ./auditd.nix
    ./autovt.nix
    ./blocky.nix
    ./bluetooth.nix
    ./colord.nix
    ./cups.nix
    ./dbus.nix
    ./display-manager.nix
    ./getty.nix
    ./NetworkManager-dispatcher.nix
    ./NetworkManager.nix
    ./nix-daemon.nix
    ./nscd.nix
    ./reload-systemd-vconsole-setup.nix
    ./rescue.nix
    ./rtkit.nix
    ./sshd.nix
    ./systemd-ask-password-console.nix
    ./systemd-ask-password-wall.nix
    ./systemd-journald.nix
    ./systemd-machined.nix
    ./systemd-rfkill.nix
    ./systemd-udevd.nix
    ./user.nix
    ./wpa_supplicant.nix
    ./clamav.nix
  ];
}
